export const PUBLIC_CHAT_REFERENCE = import.meta.env.VITE_PUBLIC_CHAT_REFERECE;
export const PUBLIC_CHAT_SYMBOL_LIMIT = 250;
export const PRIVATE_CHAT_SYMBOL_LIMIT = 250;
export const PRIVATE_CHAT_CONTACTS_DEBOUNCE_DELAY = 800; // milliseconds
export const CHAT_SCROLL_DETECTION_THRESHOLD = 80;
