export const NOTIFICATION_MESSAGE = 'NOTIFICATION_MESSAGE';
export const NOTIFICATION_ERROR = 'NOTIFICATION_ERROR';
export const NOTIFICATION_OTHER = 'NOTIFICATION_OTHER';

export const NOTIFICATION_DISPLAY_TIME = 6000;
export const NOTIFICATION_DISAPPEARING_DELAY = 1000;
